[target.aarch64-linux-android]
ar = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
linker = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android30-clang.cmd"

[target.armv7-linux-androideabi]
ar = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
linker = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi30-clang.cmd"

[target.x86_64-linux-android]
ar = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
linker = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android30-clang.cmd"

[target.i686-linux-android]
ar = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"
linker = "D:/dev-tools/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android30-clang.cmd"
